"""
Genera los archivos de idioma (en_us y las variantes de español) a partir de las tablas de abajo.

    python tools/gen_lang.py

Cada fila: clave → (inglés, español). Las variantes es_* son copia de es_es.
"""
import json
from pathlib import Path

LANG = Path(__file__).resolve().parent.parent / "src/main/resources/assets/chaostablist/lang"
SPANISH = ["es_es", "es_mx", "es_ar", "es_cl", "es_ec", "es_uy", "es_ve"]

T = {
	"yes": ("Yes", "Sí"),
	"no": ("No", "No"),
	# Pestañas
	"tab.general": ("General", "General"),
	"tab.header": ("Header", "Header"),
	"tab.footer": ("Footer", "Footer"),
	"tab.players": ("Players", "Jugadores"),
	"tab.ping": ("Ping", "Ping"),
	"tab.layout": ("Design", "Diseño"),
	"tab.animations": ("Animations", "Animaciones"),
	"tab.icons": ("Icons", "Iconos"),
	"tab.help": ("Help", "Ayuda"),
	# Botones
	"button.save": ("Save", "Guardar"),
	"button.discard": ("Discard", "Descartar"),
	"button.defaults": ("Defaults", "Por defecto"),
	"button.auto": ("Auto: %s", "Auto: %s"),
	"button.close": ("Close", "Cerrar"),
	"button.ok": ("OK", "OK"),
	"button.replay": ("▶ Open", "▶ Abrir"),
	"button.view_mod": ("View: mod", "Vista: mod"),
	"button.view_vanilla": ("View: vanilla", "Vista: vanilla"),
	"button.reset_player": ("Reset player", "Quitar cambios"),
	"button.add_threshold": ("+ Threshold", "+ Umbral"),
	# Insertar
	"insert.color": ("Color", "Color"),
	"insert.effect": ("Effect", "Efecto"),
	"insert.icon": ("Icon", "Icono"),
	"insert.data": ("Data", "Dato"),
	"popup.color": ("Pick a color (or type a hex code)", "Elige un color (o escribe el hex)"),
	"popup.effect": ("Effects and tags (click to insert)", "Efectos y etiquetas (clic para insertar)"),
	"popup.icon": ("Icons (scroll for more)", "Iconos (rueda para ver más)"),
	"popup.data": ("Placeholders", "Placeholders (datos)"),
	# Campos
	"field.enabled": ("Custom Tab enabled", "Tab personalizado activo"),
	"field.server_name": ("Server name", "Nombre server"),
	"field.update_ticks": ("Vanilla refresh (ticks)", "Refresco vanilla (ticks)"),
	"field.client_fallback": ("No-mod text", "Texto sin mod"),
	"field.sort_order": ("Sort order", "Orden"),
	"field.spectators_last": ("Spectators at the bottom", "Espectadores al final"),
	"field.id": ("ID", "ID"),
	"field.prefix": ("Prefix", "Prefijo"),
	"field.name": ("Name", "Nombre"),
	"field.suffix": ("Suffix", "Sufijo"),
	"field.hidden": ("Hidden from Tab", "Oculto del Tab"),
	"field.ping_style": ("Ping style", "Estilo del ping"),
	"field.ping_format": ("Number", "Número"),
	"field.ping_vanilla": ("Vanilla suffix", "Sufijo vanilla"),
	"field.panel_color": ("Background (top)", "Fondo (arriba)"),
	"field.panel_color2": ("Background (bottom)", "Fondo (abajo)"),
	"field.border_color": ("Border color 1", "Color borde 1"),
	"field.border_color2": ("Border color 2", "Color borde 2"),
	"field.border_width": ("Border width", "Grosor del borde"),
	"field.animated_border": ("Animated border", "Borde animado"),
	"field.rounded": ("Rounded corners", "Esquinas redondeadas"),
	"field.row_color": ("Row color", "Color de fila"),
	"field.row_alt_color": ("Alternate row", "Fila alterna"),
	"field.self_row_color": ("My row", "Mi fila"),
	"field.separator_color": ("Separator line", "Línea separadora"),
	"field.header_align": ("Header/footer align", "Alinear header/footer"),
	"field.open_animation": ("Open animation", "Animación al abrir"),
	"field.open_millis": ("Animation (ms)", "Animación (ms)"),
	"field.scale": ("Scale", "Escala"),
	"field.row_height": ("Row height", "Alto de fila"),
	"field.row_gap": ("Row gap", "Espacio entre filas"),
	"field.column_gap": ("Column gap", "Espacio entre columnas"),
	"field.padding": ("Padding", "Margen interior"),
	"field.max_rows": ("Rows per column", "Filas por columna"),
	"field.max_players": ("Max players shown", "Máx. jugadores"),
	"field.min_column": ("Min column width", "Ancho mín. columna"),
	"field.top_margin": ("Top margin", "Margen superior"),
	"field.show_heads": ("Player heads", "Cabezas"),
	"field.text_shadow": ("Text shadow", "Sombra del texto"),
	"field.singleplayer": ("Show in singleplayer", "Mostrar en un jugador"),
	"field.spectator_alpha": ("Spectator opacity", "Opacidad espectadores"),
	"field.objective_style": ("Scoreboard style", "Estilo del marcador"),
	"field.interval": ("Interval (ms)", "Intervalo (ms)"),
	# Opciones
	"opt.both": ("Bars + number", "Barras + número"),
	"opt.bars": ("Bars", "Barras"),
	"opt.number": ("Number", "Número"),
	"opt.text": ("Number only", "Solo número"),
	"opt.hidden": ("Hidden", "Oculto"),
	"opt.center": ("Center", "Centro"),
	"opt.left": ("Left", "Izquierda"),
	"opt.right": ("Right", "Derecha"),
	"opt.drop": ("Drop", "Caída"),
	"opt.fade": ("Fade", "Fundido"),
	"opt.slide": ("Slide", "Deslizar"),
	"opt.scale": ("Zoom", "Zoom"),
	"opt.none": ("None", "Ninguna"),
	"opt.hearts": ("Hearts", "Corazones"),
	"sort.rank": ("Rank", "Rango"),
	"sort.name": ("Name", "Nombre"),
	"sort.ping": ("Ping", "Ping"),
	"sort.gamemode": ("Mode", "Modo"),
	"sort.world": ("World", "Mundo"),
	"sort.team": ("Team", "Equipo"),
	# Pantalla
	"screen.subtitle": ("Edit the Tab · changes preview live", "Editor del Tab · los cambios se ven en vivo"),
	"screen.preview": ("Live preview (with mod)", "Vista previa en vivo (con mod)"),
	"screen.preview_vanilla": ("Preview: what players without the mod see",
			"Vista previa: lo que ven los que no tienen el mod"),
	"screen.header": ("Header (one line per row)", "Header (una línea por fila)"),
	"screen.footer": ("Footer (one line per row)", "Footer (una línea por fila)"),
	"screen.lines_hint": ("Type here… e.g. <gradient:#f00:#00f>Hello</gradient>",
			"Escribe aquí… ej. <gradient:#f00:#00f>Hola</gradient>"),
	"screen.hint.lines": ("Use the buttons below to insert colors, effects, icons and data.",
			"Usa los botones de abajo para meter colores, efectos, iconos y datos."),
	"screen.hint.general": ("Sort: click a key to add/remove it (order = priority).",
			"Orden: pulsa una clave para añadirla o quitarla (el orden manda)."),
	"screen.hint.players": ("Empty field = uses the default format (Chaos Ranks rank + name).",
			"Campo vacío = usa el formato normal (rango de Chaos Ranks + nombre)."),
	"screen.no_players": ("No players.", "No hay jugadores."),
	"screen.no_animations": ("No animations. Press + to create one.", "No hay animaciones. Pulsa + para crear una."),
	"screen.anim_usage": ("Frames · {anim:%s}", "Frames · {anim:%s}"),
	"screen.anim_desc": ("Your frame animation", "Tu animación por frames"),
	"screen.sample": ("Example", "Ejemplo"),
	"screen.opacity": ("Opacity", "Opacidad"),
	"screen.popup_hint": ("Hover to see what it does · click to insert", "Pasa el ratón para ver qué hace · clic para insertar"),
	"screen.empty_line": ("(empty line)", "(línea vacía)"),
	"screen.looks_like": ("Looks like:", "Así se ve:"),
	"button.code": ("Code", "Código"),
	"button.visual": ("Visual", "Visual"),
	"cat.color": ("Colors", "Colores"),
	"cat.motion": ("Motion ★", "Movimiento ★"),
	"cat.animated": ("Animated text", "Texto animado"),
	"cat.style": ("Style", "Estilo"),
	"cat.elements": ("Elements", "Elementos"),
	"cat.logic": ("Logic", "Lógica"),
	"cat.server": ("Server", "Servidor"),
	"cat.player": ("Player", "Jugador"),
	"cat.client": ("Client ★", "Cliente ★"),
	"cat.rank": ("Rank (Chaos Ranks)", "Rango (Chaos Ranks)"),
	"cat.animations": ("Animations", "Animaciones"),
	"screen.thresholds": ("Ping colors", "Colores del ping"),
	"screen.threshold_max": ("Up to", "Hasta"),
	"screen.threshold_rest": ("Rest", "Resto"),
	"screen.scroll_rows": ("Scroll for more (%s/%s)", "Rueda para ver más (%s/%s)"),
	"screen.fake": ("Examples: %s", "Ejemplos: %s"),
	"screen.icons_hint": ("Click an icon to copy its tag (use Icon in other tabs to insert).",
			"Clic en un icono para copiar su etiqueta (en otras pestañas usa Icono)."),
	"screen.help_title": ("Placeholders and tags (click to copy)", "Placeholders y etiquetas (clic para copiar)"),
	"screen.hex": ("Hex (#RRGGBB or #AARRGGBB):", "Hex (#RRGGBB o #AARRGGBB):"),
	"screen.unsaved": ("Unsaved changes", "Cambios sin guardar"),
	"screen.chaosranks_on": ("Chaos Ranks detected: {rank} and sorting by rank work.",
			"Chaos Ranks detectado: {rank} y el orden por rango funcionan."),
	"screen.chaosranks_off": ("Chaos Ranks not installed ({rank} will be empty).",
			"Chaos Ranks no está instalado ({rank} saldrá vacío)."),
	# Mensajes
	"msg.need_client": ("The Tab editor needs Chaos Tablist installed on your client.",
			"Para el editor del Tab necesitas Chaos Tablist instalado en tu cliente."),
	"msg.invalid": ("The Tab configuration sent was not valid.", "La configuración del Tab enviada no es válida."),
	"msg.saved": ("Tab saved and applied to everyone.", "Tab guardado y aplicado a todos."),
	"msg.sent": ("Saved ✔", "Guardado ✔"),
	"msg.reloaded": ("Tab configuration reloaded.", "Configuración del Tab recargada."),
	"msg.toggled": ("Custom Tab active: %s", "Tab personalizado activo: %s"),
	"msg.player_updated": ("Tab updated for %s player(s).", "Tab actualizado para %s jugador(es)."),
	"msg.copied": ("Copied: %s", "Copiado: %s"),
	"msg.too_big": ("Configuration too big to send (%s KB).", "Configuración demasiado grande para enviar (%s KB)."),
}

# ★ = solo se ve con el mod en el cliente.
SNIPPETS = {
	"gradient": ("Gradient", "Degradado"),
	"gradient_anim": ("Moving gradient", "Degradado animado"),
	"rainbow": ("Rainbow", "Arcoíris"),
	"fade": ("Color fade", "Fundido de color"),
	"pulse": ("Pulse", "Pulso"),
	"sparkle": ("Sparkles", "Destellos"),
	"wave": ("Wave ★", "Ola ★"),
	"bounce": ("Bounce ★", "Rebote ★"),
	"shake": ("Shake ★", "Temblor ★"),
	"typewriter": ("Typewriter", "Máquina de escribir"),
	"scroll": ("Marquee", "Marquesina"),
	"blink": ("Blink", "Parpadeo"),
	"cycle": ("Cycle texts", "Alternar textos"),
	"fadein": ("Fade in on open ★", "Aparecer al abrir ★"),
	"bg": ("Background ★", "Fondo ★"),
	"bg_border": ("Background + border ★", "Fondo + borde ★"),
	"outline": ("Outline ★", "Contorno ★"),
	"glow": ("Glow ★", "Brillo ★"),
	"shadow": ("Colored shadow ★", "Sombra de color ★"),
	"noshadow": ("No shadow ★", "Sin sombra ★"),
	"alpha": ("Transparency ★", "Transparencia ★"),
	"bold": ("Bold", "Negrita"),
	"italic": ("Italic", "Cursiva"),
	"underlined": ("Underline", "Subrayado"),
	"strikethrough": ("Strikethrough", "Tachado"),
	"obfuscated": ("Obfuscated", "Ofuscado"),
	"smallcaps": ("Small caps", "Versalitas"),
	"upper": ("Uppercase", "Mayúsculas"),
	"badge": ("Label with background", "Etiqueta con fondo"),
	"bar": ("Progress bar", "Barra de progreso"),
	"pc": ("Color by ping", "Color según ping"),
	"scale": ("Color by value", "Color según valor"),
	"if": ("Condition (if/else)", "Condición (si/si no)"),
	"head": ("Player head ★", "Cabeza ★"),
	"item": ("Item ★", "Ítem ★"),
	"image": ("Custom PNG icon ★", "Icono PNG propio ★"),
	"image_big": ("Big custom image ★", "Imagen grande ★"),
	"space": ("Space (pixels)", "Espacio (píxeles)"),
	"br": ("Line break", "Salto de línea"),
	"left": ("Align left", "Alinear izquierda"),
	"center": ("Align center", "Centrar"),
	"right": ("Align right", "Alinear derecha"),
	"font": ("Font", "Fuente"),
	"legacy": ("Legacy &codes", "Códigos & clásicos"),
}

DESCS = {
	"gradient": ("Colors blend from one to another along the text", "Los colores pasan de uno a otro a lo largo del texto"),
	"gradient_anim": ("A gradient that keeps sliding", "Un degradado que se va desplazando"),
	"rainbow": ("All the colors of the rainbow, moving", "Todos los colores del arcoíris, en movimiento"),
	"fade": ("The whole text changes color smoothly", "Todo el texto cambia de color suavemente"),
	"pulse": ("Breathes towards a color and back", "Respira hacia un color y vuelve"),
	"sparkle": ("Random letters flash", "Letras al azar que destellan"),
	"wave": ("Letters move up and down like a wave", "Las letras suben y bajan como una ola"),
	"bounce": ("Letters jump one after another", "Las letras saltan una tras otra"),
	"shake": ("The text trembles", "El texto tiembla"),
	"fadein": ("Appears letter by letter when the Tab opens", "Aparece letra a letra al abrir el Tab"),
	"typewriter": ("Types itself letter by letter", "Se escribe solo letra a letra"),
	"scroll": ("Long text that scrolls inside a fixed width", "Texto largo que se desplaza en un ancho fijo"),
	"blink": ("Turns on and off", "Se enciende y se apaga"),
	"cycle": ("Shows one text after another", "Muestra un texto tras otro"),
	"bold": ("Bold text", "Texto en negrita"),
	"italic": ("Italic text", "Texto en cursiva"),
	"underlined": ("Underlined text", "Texto subrayado"),
	"strikethrough": ("Crossed-out text", "Texto tachado"),
	"obfuscated": ("Constantly changing letters", "Letras que cambian sin parar"),
	"smallcaps": ("Small capital letters", "Mayúsculas pequeñas"),
	"upper": ("Turns everything to uppercase", "Lo pasa todo a mayúsculas"),
	"bg": ("A box behind the text", "Un recuadro detrás del texto"),
	"bg_border": ("A box with a border behind the text", "Un recuadro con borde detrás del texto"),
	"outline": ("A line around each letter", "Una línea alrededor de cada letra"),
	"glow": ("A soft glow around the letters", "Un brillo suave alrededor de las letras"),
	"shadow": ("Shadow in the color you choose", "Sombra del color que elijas"),
	"noshadow": ("Removes the shadow", "Quita la sombra"),
	"alpha": ("Semi-transparent text", "Texto semitransparente"),
	"font": ("Another Minecraft font", "Otra fuente de Minecraft"),
	"bar": ("A bar that fills with a value (RAM, health…)", "Una barra que se llena con un valor (RAM, vida…)"),
	"badge": ("Pixel label with background and icon (for header/footer)", "Etiqueta pixel con fondo e icono (para header/footer)"),
	"head": ("The player's head", "La cabeza del jugador"),
	"item": ("A Minecraft item", "Un ítem de Minecraft"),
	"image": ("Your PNG from the icons folder", "Tu PNG de la carpeta icons"),
	"image_big": ("Your PNG at a custom size", "Tu PNG con el tamaño que quieras"),
	"space": ("Empty space in pixels", "Espacio vacío en píxeles"),
	"br": ("Starts a new line", "Empieza una línea nueva"),
	"left": ("Aligns the line to the left", "Alinea la línea a la izquierda"),
	"center": ("Centers the line", "Centra la línea"),
	"right": ("Aligns the line to the right", "Alinea la línea a la derecha"),
	"pc": ("Green if the ping is good, red if it's bad", "Verde si el ping es bueno, rojo si es malo"),
	"scale": ("Color depending on a value", "Color según un valor"),
	"if": ("Shows one thing or another", "Muestra una cosa u otra"),
	"legacy": ("Classic &a color codes", "Códigos de color & clásicos"),
}

PLACEHOLDERS = {
	"player": ("player name", "nombre del jugador"),
	"ping": ("ping in ms", "ping en ms"),
	"online": ("players online", "jugadores conectados"),
	"max_players": ("max players", "máximo de jugadores"),
	"server_name": ("server name", "nombre del server"),
	"tps": ("server TPS", "TPS del server"),
	"mspt": ("ms per tick", "ms por tick"),
	"ram": ("server RAM", "RAM del server"),
	"ram_pct": ("server RAM %", "RAM del server %"),
	"ram_used": ("used RAM (MB)", "RAM usada (MB)"),
	"ram_max": ("max RAM (MB)", "RAM máxima (MB)"),
	"cpu": ("server CPU %", "CPU del server %"),
	"uptime": ("uptime", "tiempo encendido"),
	"fps": ("your FPS ★", "tus FPS ★"),
	"client_ram": ("your RAM ★", "tu RAM ★"),
	"client_ram_pct": ("your RAM % ★", "tu RAM % ★"),
	"my_ping": ("your ping", "tu ping"),
	"local_time": ("your clock", "tu hora"),
	"local_time_s": ("your clock + seconds", "tu hora + segundos"),
	"local_date": ("your date", "tu fecha"),
	"date": ("server date", "fecha del server"),
	"time": ("server time", "hora del server"),
	"world": ("world", "mundo"),
	"dimension": ("dimension id", "id de dimensión"),
	"biome": ("biome", "bioma"),
	"x": ("X", "X"),
	"y": ("Y", "Y"),
	"z": ("Z", "Z"),
	"health": ("health", "vida"),
	"max_health": ("max health", "vida máxima"),
	"food": ("food", "comida"),
	"level": ("XP level", "nivel de XP"),
	"gamemode": ("game mode", "modo de juego"),
	"deaths": ("deaths", "muertes"),
	"kills": ("player kills", "asesinatos"),
	"mob_kills": ("mob kills", "mobs matados"),
	"playtime": ("play time", "tiempo jugado"),
	"afk": ("AFK (true/false)", "AFK (true/false)"),
	"op": ("is OP", "es OP"),
	"team": ("team", "equipo"),
	"rank": ("Chaos Ranks badge", "badge de Chaos Ranks"),
	"rank_name": ("rank name", "nombre del rango"),
	"has_rank": ("has a rank", "tiene rango"),
	"day": ("world day", "día del mundo"),
	"world_time": ("world clock", "hora del mundo"),
	"weather": ("weather", "clima"),
	"weather_icon": ("weather symbol", "símbolo del clima"),
	"motd": ("MOTD", "MOTD"),
	"version": ("MC version", "versión de MC"),
}

COLORS = {
	"dark_red": ("Dark red", "Rojo oscuro"), "red": ("Red", "Rojo"), "light_red": ("Light red", "Rojo claro"),
	"coral": ("Coral", "Coral"), "salmon": ("Salmon", "Salmón"), "orange": ("Orange", "Naranja"),
	"light_orange": ("Light orange", "Naranja claro"), "copper": ("Copper", "Cobre"),
	"gold": ("Gold", "Oro"), "amber": ("Amber", "Ámbar"), "yellow": ("Yellow", "Amarillo"),
	"light_yellow": ("Light yellow", "Amarillo claro"), "cream": ("Cream", "Crema"), "mustard": ("Mustard", "Mostaza"),
	"lime": ("Lime", "Lima"), "neon_green": ("Neon green", "Verde neón"), "mint": ("Mint", "Menta"),
	"emerald": ("Emerald", "Esmeralda"), "green": ("Green", "Verde"), "dark_green": ("Dark green", "Verde oscuro"),
	"olive": ("Olive", "Oliva"), "turquoise": ("Turquoise", "Turquesa"),
	"diamond": ("Diamond", "Diamante"), "cyan": ("Cyan", "Cian"), "sky": ("Sky", "Cielo"),
	"light_blue": ("Light blue", "Celeste"), "blue": ("Blue", "Azul"), "lapis": ("Lapis", "Lapislázuli"),
	"navy": ("Navy", "Azul marino"), "ice": ("Ice", "Hielo"),
	"purple": ("Purple", "Morado"), "amethyst": ("Amethyst", "Amatista"), "lavender": ("Lavender", "Lavanda"),
	"violet": ("Violet", "Violeta"), "magenta": ("Magenta", "Magenta"), "pink": ("Pink", "Rosa"),
	"light_pink": ("Light pink", "Rosa claro"), "hot_pink": ("Hot pink", "Rosa fuerte"),
	"brown": ("Brown", "Marrón"), "dark_brown": ("Dark brown", "Marrón oscuro"), "sand": ("Sand", "Arena"),
	"tan": ("Tan", "Canela"), "rust": ("Rust", "Óxido"), "wine": ("Wine", "Vino"),
	"white": ("White", "Blanco"), "light_gray": ("Light gray", "Gris claro"), "silver": ("Silver", "Plata"),
	"gray": ("Gray", "Gris"), "dark_gray": ("Dark gray", "Gris oscuro"), "charcoal": ("Charcoal", "Carbón"),
	"black": ("Black", "Negro"), "obsidian": ("Obsidian", "Obsidiana"),
	"youtube": ("YouTube", "YouTube"), "twitch": ("Twitch", "Twitch"), "discord": ("Discord", "Discord"),
	"kick": ("Kick", "Kick"), "spotify": ("Spotify", "Spotify"), "tiktok": ("TikTok", "TikTok"),
	"instagram": ("Instagram", "Instagram"), "twitter": ("Twitter / X", "Twitter / X"),
}


def main():
	en, es = {}, {}
	for table, prefix, suffix in ((T, "", ""), (SNIPPETS, "snippet.", ""), (DESCS, "snippet.", ".desc"),
			(PLACEHOLDERS, "ph.", ""), (COLORS, "color.", "")):
		for k, (e, s) in table.items():
			en["chaostablist." + prefix + k + suffix] = e
			es["chaostablist." + prefix + k + suffix] = s
	LANG.mkdir(parents=True, exist_ok=True)
	(LANG / "en_us.json").write_text(json.dumps(en, indent="\t", ensure_ascii=False) + "\n", encoding="utf-8")
	for name in SPANISH:
		(LANG / f"{name}.json").write_text(json.dumps(es, indent="\t", ensure_ascii=False) + "\n", encoding="utf-8")
	print(len(en), "claves")


if __name__ == "__main__":
	main()
