"""
Genera los archivos de idioma (en_us y las variantes de español) a partir de las tablas de abajo.

    python tools/gen_lang.py

Cada fila: clave → (inglés, español). Las variantes es_* son copia de es_es.
"""
import json
from pathlib import Path

LANG = Path(__file__).resolve().parent.parent / "src/main/resources/assets/chaostablist/lang"
SPANISH = ["es_es", "es_mx", "es_ar", "es_cl", "es_ec", "es_uy", "es_ve"]

T = {
	"yes": ("Yes", "Sí"),
	"no": ("No", "No"),
	# Pestañas
	"tab.general": ("General", "General"),
	"tab.header": ("Header", "Header"),
	"tab.footer": ("Footer", "Footer"),
	"tab.players": ("Players", "Jugadores"),
	"tab.ping": ("Ping", "Ping"),
	"tab.layout": ("Design", "Diseño"),
	"tab.animations": ("Animations", "Animaciones"),
	"tab.icons": ("Icons", "Iconos"),
	"tab.help": ("Help", "Ayuda"),
	# Botones
	"button.save": ("Save", "Guardar"),
	"button.discard": ("Discard", "Descartar"),
	"button.defaults": ("Defaults", "Por defecto"),
	"button.auto": ("Auto: %s", "Auto: %s"),
	"button.close": ("Close", "Cerrar"),
	"button.ok": ("OK", "OK"),
	"button.replay": ("▶ Open", "▶ Abrir"),
	"button.view_mod": ("View: mod", "Vista: mod"),
	"button.view_vanilla": ("View: vanilla", "Vista: vanilla"),
	"button.reset_player": ("Reset player", "Quitar cambios"),
	"button.add_threshold": ("+ Threshold", "+ Umbral"),
	# Insertar
	"insert.color": ("Color", "Color"),
	"insert.effect": ("Effect", "Efecto"),
	"insert.icon": ("Icon", "Icono"),
	"insert.data": ("Data", "Dato"),
	"popup.color": ("Pick a color (or type a hex code)", "Elige un color (o escribe el hex)"),
	"popup.effect": ("Effects and tags (click to insert)", "Efectos y etiquetas (clic para insertar)"),
	"popup.icon": ("Icons (scroll for more)", "Iconos (rueda para ver más)"),
	"popup.data": ("Placeholders", "Placeholders (datos)"),
	# Campos
	"field.enabled": ("Custom Tab enabled", "Tab personalizado activo"),
	"field.server_name": ("Server name", "Nombre server"),
	"field.update_ticks": ("Vanilla refresh (ticks)", "Refresco vanilla (ticks)"),
	"field.client_fallback": ("No-mod text", "Texto sin mod"),
	"field.sort_order": ("Sort order", "Orden"),
	"field.spectators_last": ("Spectators at the bottom", "Espectadores al final"),
	"field.id": ("ID", "ID"),
	"field.prefix": ("Prefix", "Prefijo"),
	"field.name": ("Name", "Nombre"),
	"field.suffix": ("Suffix", "Sufijo"),
	"field.hidden": ("Hidden from Tab", "Oculto del Tab"),
	"field.ping_style": ("Ping style", "Estilo del ping"),
	"field.ping_format": ("Number", "Número"),
	"field.ping_vanilla": ("Vanilla suffix", "Sufijo vanilla"),
	"field.panel_color": ("Background (top)", "Fondo (arriba)"),
	"field.panel_color2": ("Background (bottom)", "Fondo (abajo)"),
	"field.border_color": ("Border color 1", "Color borde 1"),
	"field.border_color2": ("Border color 2", "Color borde 2"),
	"field.border_width": ("Border width", "Grosor del borde"),
	"field.animated_border": ("Animated border", "Borde animado"),
	"field.rounded": ("Rounded corners", "Esquinas redondeadas"),
	"field.row_color": ("Row color", "Color de fila"),
	"field.row_alt_color": ("Alternate row", "Fila alterna"),
	"field.self_row_color": ("My row", "Mi fila"),
	"field.separator_color": ("Separator line", "Línea separadora"),
	"field.header_align": ("Header/footer align", "Alinear header/footer"),
	"field.open_animation": ("Open animation", "Animación al abrir"),
	"field.open_millis": ("Animation (ms)", "Animación (ms)"),
	"field.scale": ("Scale", "Escala"),
	"field.row_height": ("Row height", "Alto de fila"),
	"field.row_gap": ("Row gap", "Espacio entre filas"),
	"field.column_gap": ("Column gap", "Espacio entre columnas"),
	"field.padding": ("Padding", "Margen interior"),
	"field.max_rows": ("Rows per column", "Filas por columna"),
	"field.max_players": ("Max players shown", "Máx. jugadores"),
	"field.min_column": ("Min column width", "Ancho mín. columna"),
	"field.top_margin": ("Top margin", "Margen superior"),
	"field.show_heads": ("Player heads", "Cabezas"),
	"field.text_shadow": ("Text shadow", "Sombra del texto"),
	"field.singleplayer": ("Show in singleplayer", "Mostrar en un jugador"),
	"field.spectator_alpha": ("Spectator opacity", "Opacidad espectadores"),
	"field.objective_style": ("Scoreboard style", "Estilo del marcador"),
	"field.interval": ("Interval (ms)", "Intervalo (ms)"),
	# Opciones
	"opt.both": ("Bars + number", "Barras + número"),
	"opt.bars": ("Bars", "Barras"),
	"opt.number": ("Number", "Número"),
	"opt.text": ("Number only", "Solo número"),
	"opt.hidden": ("Hidden", "Oculto"),
	"opt.center": ("Center", "Centro"),
	"opt.left": ("Left", "Izquierda"),
	"opt.right": ("Right", "Derecha"),
	"opt.drop": ("Drop", "Caída"),
	"opt.fade": ("Fade", "Fundido"),
	"opt.slide": ("Slide", "Deslizar"),
	"opt.scale": ("Zoom", "Zoom"),
	"opt.none": ("None", "Ninguna"),
	"opt.hearts": ("Hearts", "Corazones"),
	"sort.rank": ("Rank", "Rango"),
	"sort.name": ("Name", "Nombre"),
	"sort.ping": ("Ping", "Ping"),
	"sort.gamemode": ("Mode", "Modo"),
	"sort.world": ("World", "Mundo"),
	"sort.team": ("Team", "Equipo"),
	# Pantalla
	"screen.subtitle": ("Edit the Tab · changes preview live", "Editor del Tab · los cambios se ven en vivo"),
	"screen.preview": ("Live preview (with mod)", "Vista previa en vivo (con mod)"),
	"screen.preview_vanilla": ("Preview: what players without the mod see",
			"Vista previa: lo que ven los que no tienen el mod"),
	"screen.header": ("Header (one line per row)", "Header (una línea por fila)"),
	"screen.footer": ("Footer (one line per row)", "Footer (una línea por fila)"),
	"screen.lines_hint": ("Type here… e.g. <gradient:#f00:#00f>Hello</gradient>",
			"Escribe aquí… ej. <gradient:#f00:#00f>Hola</gradient>"),
	"screen.hint.lines": ("Use the buttons below to insert colors, effects, icons and data.",
			"Usa los botones de abajo para meter colores, efectos, iconos y datos."),
	"screen.hint.general": ("Sort: click a key to add/remove it (order = priority).",
			"Orden: pulsa una clave para añadirla o quitarla (el orden manda)."),
	"screen.hint.players": ("Empty field = uses the default format (Chaos Ranks rank + name).",
			"Campo vacío = usa el formato normal (rango de Chaos Ranks + nombre)."),
	"screen.no_players": ("No players.", "No hay jugadores."),
	"screen.no_animations": ("No animations. Press + to create one.", "No hay animaciones. Pulsa + para crear una."),
	"screen.anim_usage": ("Frames · {anim:%s}", "Frames · {anim:%s}"),
	"screen.anim_desc": ("Your frame animation", "Tu animación por frames"),
	"screen.sample": ("Example", "Ejemplo"),
	"screen.opacity": ("Opacity", "Opacidad"),
	"screen.popup_hint": ("Hover to see what it does · click to insert", "Pasa el ratón para ver qué hace · clic para insertar"),
	"screen.empty_line": ("(empty line)", "(línea vacía)"),
	"screen.looks_like": ("Looks like:", "Así se ve:"),
	"button.code": ("Code", "Código"),
	"button.visual": ("Visual", "Visual"),
	"cat.color": ("Colors", "Colores"),
	"cat.motion": ("Motion ★", "Movimiento ★"),
	"cat.animated": ("Animated text", "Texto animado"),
	"cat.style": ("Style", "Estilo"),
	"cat.elements": ("Elements", "Elementos"),
	"cat.logic": ("Logic", "Lógica"),
	"cat.server": ("Server", "Servidor"),
	"cat.player": ("Player", "Jugador"),
	"cat.client": ("Client ★", "Cliente ★"),
	"cat.rank": ("Rank (Chaos Ranks)", "Rango (Chaos Ranks)"),
	"cat.animations": ("Animations", "Animaciones"),
	"screen.thresholds": ("Ping colors", "Colores del ping"),
	"screen.threshold_max": ("Up to", "Hasta"),
	"screen.threshold_rest": ("Rest", "Resto"),
	"screen.scroll_rows": ("Scroll for more (%s/%s)", "Rueda para ver más (%s/%s)"),
	"screen.fake": ("Examples: %s", "Ejemplos: %s"),
	"screen.icons_hint": ("Click an icon to copy its tag (use Icon in other tabs to insert).",
			"Clic en un icono para copiar su etiqueta (en otras pestañas usa Icono)."),
	"screen.help_title": ("Placeholders and tags (click to copy)", "Placeholders y etiquetas (clic para copiar)"),
	"screen.hex": ("Hex (#RRGGBB or #AARRGGBB):", "Hex (#RRGGBB o #AARRGGBB):"),
	"screen.unsaved": ("Unsaved changes", "Cambios sin guardar"),
	"screen.chaosranks_on": ("Chaos Ranks detected: {rank} and sorting by rank work.",
			"Chaos Ranks detectado: {rank} y el orden por rango funcionan."),
	"screen.chaosranks_off": ("Chaos Ranks not installed ({rank} will be empty).",
			"Chaos Ranks no está instalado ({rank} saldrá vacío)."),
	# Tooltips y editor de efectos
	"tab.general.tip": ("Basics: turn the custom Tab on/off, server name, player order and how often vanilla clients refresh.",
			"Lo básico: activar el Tab, nombre del servidor, orden de los jugadores y cada cuánto se actualiza en vanilla."),
	"tab.header.tip": ("The lines above the player list. Double-click a line to edit it right there.",
			"Las líneas de arriba de la lista de jugadores. Doble clic en una línea para editarla ahí mismo."),
	"tab.footer.tip": ("The lines below the player list. Double-click a line to edit it right there.",
			"Las líneas de abajo de la lista de jugadores. Doble clic en una línea para editarla ahí mismo."),
	"tab.players.tip": ("Give one player their own prefix, name or suffix, or hide them from the Tab.",
			"Dale a un jugador concreto su propio prefijo, nombre o sufijo, u ocúltalo del Tab."),
	"tab.ping.tip": ("How the ping looks: bars, number, colors by threshold and what players without the mod see.",
			"Cómo se ve el ping: barras, número, colores por umbral y lo que ven los que no tienen el mod."),
	"tab.layout.tip": ("Look of the panel: background, border, rows, columns, scale and opening animation (mod only).",
			"Aspecto del panel: fondo, borde, filas, columnas, escala y animación al abrir (solo con el mod)."),
	"tab.animations.tip": ("Frame animations: each line is a frame. Use them anywhere with {anim:name}.",
			"Animaciones por frames: cada línea es un frame. Se usan en cualquier sitio con {anim:nombre}."),
	"tab.icons.tip": ("Every icon you can use. Click one to copy its tag.",
			"Todos los iconos que puedes usar. Clic en uno para copiar su etiqueta."),
	"tab.help.tip": ("Every placeholder with its current value and every tag with a live example. Click to copy.",
			"Todos los datos con su valor actual y todas las etiquetas con un ejemplo en vivo. Clic para copiar."),
	"insert.color.tip": ("Pick a color and put it at the cursor (it colors the selected text if there is one).",
			"Elige un color y lo mete en el cursor (si hay texto seleccionado, colorea solo ese texto)."),
	"insert.effect.tip": ("Gradients, animations, styles… Click to insert, or ✎ to configure it first.",
			"Degradados, animaciones, estilos… Clic para insertarlo, o ✎ para configurarlo antes."),
	"insert.icon.tip": ("Insert one of the pixel-art icons at the cursor.",
			"Mete uno de los iconos pixel art en el cursor."),
	"insert.data.tip": ("Insert a placeholder (TPS, ping, player…) that shows live data.",
			"Mete un dato (TPS, ping, jugador…) que se actualiza solo."),
	"button.save.tip": ("Save and apply the Tab to the whole server right now.",
			"Guarda y aplica el Tab a todo el servidor al momento."),
	"button.discard.tip": ("Undo everything since the last save (Ctrl+Z brings it back).",
			"Deshace todo lo cambiado desde la última vez que guardaste (Ctrl+Z lo recupera)."),
	"button.defaults.tip": ("Load the default configuration (nothing is saved until you press Save).",
			"Carga la configuración por defecto (no se guarda hasta que pulses Guardar)."),
	"button.auto.tip": ("When on, changes are saved by themselves while you type.",
			"Si está activo, los cambios se guardan solos mientras escribes."),
	"button.close.tip": ("Close the editor (anything not saved is not applied).",
			"Cierra el editor (lo que no hayas guardado no se aplica)."),
	"button.view.tip": ("Switch the preview between players with the mod and players without it.",
			"Cambia la vista previa entre lo que ven los jugadores con el mod y sin él."),
	"button.replay.tip": ("Play the opening animation again.",
			"Repite la animación al abrir el Tab."),
	"button.fakes.tip": ("Example players shown in the preview.",
			"Jugadores de ejemplo en la vista previa."),
	"button.ok.tip": ("Use this color.",
			"Usar este color."),
	"button.preview": ("Preview",
			"Vista previa"),
	"button.preview_off": ("Undo preview",
			"Quitar vista"),
	"button.preview.tip": ("Try the color in the live preview. It is only kept if you press OK.",
			"Prueba el color en la vista previa en vivo. Solo se queda si pulsas OK."),
	"button.code.tip": ("Switch between the line list and a plain text box (handy for pasting many lines).",
			"Cambia entre la lista de líneas y un cuadro de texto normal (útil para pegar muchas líneas)."),
	"button.line_up.tip": ("Move the selected line up.",
			"Sube la línea seleccionada."),
	"button.line_down.tip": ("Move the selected line down.",
			"Baja la línea seleccionada."),
	"button.line_add.tip": ("Add an empty line below the selected one.",
			"Añade una línea vacía debajo de la seleccionada."),
	"button.line_remove.tip": ("Delete the selected line.",
			"Borra la línea seleccionada."),
	"screen.line_field.tip": ("Here you edit the selected line (highlighted above). You can also double-click a line to edit it right there. Ctrl+Z undoes, Ctrl+Y redoes.",
			"Aquí editas la línea seleccionada (la resaltada arriba). También puedes hacer doble clic en una línea para editarla ahí mismo. Ctrl+Z deshace y Ctrl+Y rehace."),
	"screen.lines.tip": ("Click a line to select it and edit it in the field below · double-click to edit it right here.",
			"Clic en una línea para elegirla y editarla en el campo de abajo · doble clic para editarla aquí mismo."),
	"popup.effect_edit": ("Edit: %s",
			"Editar: %s"),
	"popup.icon_pick": ("Pick an icon for the effect",
			"Elige un icono para el efecto"),
	"screen.edit_effect_hint": ("✎ Configure colors, speed, text or icon before inserting it",
			"✎ Configura colores, velocidad, texto o icono antes de insertarlo"),
	"screen.no_params": ("This effect has nothing to configure.",
			"Este efecto no tiene nada que configurar."),
	"button.back": ("← Back",
			"← Volver"),
	"button.back.tip": ("Back to the effect list without inserting anything.",
			"Vuelve a la lista de efectos sin insertar nada."),
	"button.insert": ("Insert",
			"Insertar"),
	"button.insert.tip": ("Insert the effect at the cursor of the last field you used.",
			"Mete el efecto en el cursor del último campo que usaste."),
	"button.reset": ("Reset",
			"Reiniciar"),
	"button.reset.tip": ("Back to the default values.",
			"Vuelve a los valores por defecto."),
	"button.pick_icon": ("Pick icon…",
			"Elegir icono…"),
	"button.pick_icon.tip": ("Choose which icon goes inside the effect.",
			"Elige qué icono va dentro del efecto."),
	"body.text": ("Text",
			"Texto"),
	"body.icon": ("Icon",
			"Icono"),
	"body.tip": ("What goes inside the effect: a text you write or an icon.",
			"Qué va dentro del efecto: un texto que escribes o un icono."),
	"param.body": ("Content",
			"Contenido"),
	"param.c1": ("Color 1",
			"Color 1"),
	"param.c2": ("Color 2",
			"Color 2"),
	"param.c3": ("Color 3",
			"Color 3"),
	"param.speed": ("Speed",
			"Velocidad"),
	"param.sat": ("Saturation",
			"Saturación"),
	"param.density": ("Density",
			"Densidad"),
	"param.amp": ("Height",
			"Altura"),
	"param.strength": ("Strength",
			"Fuerza"),
	"param.time": ("Duration (s)",
			"Duración (s)"),
	"param.stagger": ("Delay per letter",
			"Retraso por letra"),
	"param.pause": ("Pause (s)",
			"Pausa (s)"),
	"param.cursor": ("Cursor",
			"Cursor"),
	"param.width": ("Width",
			"Ancho"),
	"param.on": ("Visible (s)",
			"Visible (s)"),
	"param.off": ("Hidden (s)",
			"Oculto (s)"),
	"param.interval": ("Every (s)",
			"Cada (s)"),
	"param.fade": ("Fade between",
			"Fundido"),
	"param.t1": ("Text 1",
			"Texto 1"),
	"param.t2": ("Text 2",
			"Texto 2"),
	"param.t3": ("Text 3",
			"Texto 3"),
	"param.pad": ("Margin",
			"Margen"),
	"param.round": ("Rounded",
			"Redondeado"),
	"param.border": ("Border",
			"Borde"),
	"param.value": ("Value",
			"Valor"),
	"param.font": ("Font",
			"Fuente"),
	"param.char": ("Character",
			"Carácter"),
	"param.to": ("Full color",
			"Color lleno"),
	"param.text": ("Text",
			"Texto"),
	"param.bg": ("Background",
			"Fondo"),
	"param.fg": ("Text color",
			"Color letras"),
	"param.icon": ("Icon",
			"Icono"),
	"param.frame": ("Frame",
			"Marco"),
	"param.bold": ("Bold",
			"Negrita"),
	"param.player": ("Player",
			"Jugador"),
	"param.item": ("Item",
			"Ítem"),
	"param.name": ("File",
			"Archivo"),
	"param.w": ("Width",
			"Ancho"),
	"param.h": ("Height",
			"Alto"),
	"param.px": ("Pixels",
			"Píxeles"),
	"param.min": ("Minimum",
			"Mínimo"),
	"param.max": ("Maximum",
			"Máximo"),
	"param.a": ("Value",
			"Valor"),
	"param.op": ("Compare",
			"Comparar"),
	"param.b": ("With",
			"Con"),
	"param.yes": ("If yes",
			"Si se cumple"),
	"param.no": ("If not",
			"Si no"),
	# Mensajes
	"msg.need_client": ("The Tab editor needs Chaos Tablist installed on your client.",
			"Para el editor del Tab necesitas Chaos Tablist instalado en tu cliente."),
	"msg.invalid": ("The Tab configuration sent was not valid.", "La configuración del Tab enviada no es válida."),
	"msg.saved": ("Tab saved and applied to everyone.", "Tab guardado y aplicado a todos."),
	"msg.sent": ("Saved ✔", "Guardado ✔"),
	"msg.reloaded": ("Tab configuration reloaded.", "Configuración del Tab recargada."),
	"msg.toggled": ("Custom Tab active: %s", "Tab personalizado activo: %s"),
	"msg.player_updated": ("Tab updated for %s player(s).", "Tab actualizado para %s jugador(es)."),
	"msg.undo": ("Undone (Ctrl+Y to redo)", "Deshecho (Ctrl+Y para rehacer)"),
	"msg.redo": ("Redone", "Rehecho"),
	"msg.nothing_undo": ("Nothing to undo", "No hay nada que deshacer"),
	"msg.nothing_redo": ("Nothing to redo", "No hay nada que rehacer"),
	"msg.copied": ("Copied: %s", "Copiado: %s"),
	"msg.too_big": ("Configuration too big to send (%s KB).", "Configuración demasiado grande para enviar (%s KB)."),
}

# ★ = solo se ve con el mod en el cliente.
SNIPPETS = {
	"gradient": ("Gradient", "Degradado"),
	"gradient_anim": ("Moving gradient", "Degradado animado"),
	"rainbow": ("Rainbow", "Arcoíris"),
	"fade": ("Color fade", "Fundido de color"),
	"pulse": ("Pulse", "Pulso"),
	"sparkle": ("Sparkles", "Destellos"),
	"wave": ("Wave ★", "Ola ★"),
	"bounce": ("Bounce ★", "Rebote ★"),
	"shake": ("Shake ★", "Temblor ★"),
	"typewriter": ("Typewriter", "Máquina de escribir"),
	"scroll": ("Marquee", "Marquesina"),
	"blink": ("Blink", "Parpadeo"),
	"cycle": ("Cycle texts", "Alternar textos"),
	"fadein": ("Fade in on open ★", "Aparecer al abrir ★"),
	"bg": ("Background ★", "Fondo ★"),
	"bg_border": ("Background + border ★", "Fondo + borde ★"),
	"outline": ("Outline ★", "Contorno ★"),
	"glow": ("Glow ★", "Brillo ★"),
	"shadow": ("Colored shadow ★", "Sombra de color ★"),
	"noshadow": ("No shadow ★", "Sin sombra ★"),
	"alpha": ("Transparency ★", "Transparencia ★"),
	"bold": ("Bold", "Negrita"),
	"italic": ("Italic", "Cursiva"),
	"underlined": ("Underline", "Subrayado"),
	"strikethrough": ("Strikethrough", "Tachado"),
	"obfuscated": ("Obfuscated", "Ofuscado"),
	"smallcaps": ("Small caps", "Versalitas"),
	"upper": ("Uppercase", "Mayúsculas"),
	"badge": ("Label with background", "Etiqueta con fondo"),
	"bar": ("Progress bar", "Barra de progreso"),
	"pc": ("Color by ping", "Color según ping"),
	"scale": ("Color by value", "Color según valor"),
	"if": ("Condition (if/else)", "Condición (si/si no)"),
	"head": ("Player head ★", "Cabeza ★"),
	"item": ("Item ★", "Ítem ★"),
	"image": ("Custom PNG icon ★", "Icono PNG propio ★"),
	"image_big": ("Big custom image ★", "Imagen grande ★"),
	"space": ("Space (pixels)", "Espacio (píxeles)"),
	"br": ("Line break", "Salto de línea"),
	"left": ("Align left", "Alinear izquierda"),
	"center": ("Align center", "Centrar"),
	"right": ("Align right", "Alinear derecha"),
	"font": ("Font", "Fuente"),
	"legacy": ("Legacy &codes", "Códigos & clásicos"),
}

DESCS = {
	"gradient": ("Colors blend from one to another along the text", "Los colores pasan de uno a otro a lo largo del texto"),
	"gradient_anim": ("A gradient that keeps sliding", "Un degradado que se va desplazando"),
	"rainbow": ("All the colors of the rainbow, moving", "Todos los colores del arcoíris, en movimiento"),
	"fade": ("The whole text changes color smoothly", "Todo el texto cambia de color suavemente"),
	"pulse": ("Breathes towards a color and back", "Respira hacia un color y vuelve"),
	"sparkle": ("Random letters flash", "Letras al azar que destellan"),
	"wave": ("Letters move up and down like a wave", "Las letras suben y bajan como una ola"),
	"bounce": ("Letters jump one after another", "Las letras saltan una tras otra"),
	"shake": ("The text trembles", "El texto tiembla"),
	"fadein": ("Appears letter by letter when the Tab opens", "Aparece letra a letra al abrir el Tab"),
	"typewriter": ("Types itself letter by letter", "Se escribe solo letra a letra"),
	"scroll": ("Long text that scrolls inside a fixed width", "Texto largo que se desplaza en un ancho fijo"),
	"blink": ("Turns on and off", "Se enciende y se apaga"),
	"cycle": ("Shows one text after another", "Muestra un texto tras otro"),
	"bold": ("Bold text", "Texto en negrita"),
	"italic": ("Italic text", "Texto en cursiva"),
	"underlined": ("Underlined text", "Texto subrayado"),
	"strikethrough": ("Crossed-out text", "Texto tachado"),
	"obfuscated": ("Constantly changing letters", "Letras que cambian sin parar"),
	"smallcaps": ("Small capital letters", "Mayúsculas pequeñas"),
	"upper": ("Turns everything to uppercase", "Lo pasa todo a mayúsculas"),
	"bg": ("A box behind the text", "Un recuadro detrás del texto"),
	"bg_border": ("A box with a border behind the text", "Un recuadro con borde detrás del texto"),
	"outline": ("A line around each letter", "Una línea alrededor de cada letra"),
	"glow": ("A soft glow around the letters", "Un brillo suave alrededor de las letras"),
	"shadow": ("Shadow in the color you choose", "Sombra del color que elijas"),
	"noshadow": ("Removes the shadow", "Quita la sombra"),
	"alpha": ("Semi-transparent text", "Texto semitransparente"),
	"font": ("Another Minecraft font", "Otra fuente de Minecraft"),
	"bar": ("A bar that fills with a value (RAM, health…)", "Una barra que se llena con un valor (RAM, vida…)"),
	"badge": ("Pixel label with background and icon (for header/footer)", "Etiqueta pixel con fondo e icono (para header/footer)"),
	"head": ("The player's head", "La cabeza del jugador"),
	"item": ("A Minecraft item", "Un ítem de Minecraft"),
	"image": ("Your PNG from the icons folder", "Tu PNG de la carpeta icons"),
	"image_big": ("Your PNG at a custom size", "Tu PNG con el tamaño que quieras"),
	"space": ("Empty space in pixels", "Espacio vacío en píxeles"),
	"br": ("Starts a new line", "Empieza una línea nueva"),
	"left": ("Aligns the line to the left", "Alinea la línea a la izquierda"),
	"center": ("Centers the line", "Centra la línea"),
	"right": ("Aligns the line to the right", "Alinea la línea a la derecha"),
	"pc": ("Green if the ping is good, red if it's bad", "Verde si el ping es bueno, rojo si es malo"),
	"scale": ("Color depending on a value", "Color según un valor"),
	"if": ("Shows one thing or another", "Muestra una cosa u otra"),
	"legacy": ("Classic &a color codes", "Códigos de color & clásicos"),
}

PLACEHOLDERS = {
	"player": ("player name", "nombre del jugador"),
	"ping": ("ping in ms", "ping en ms"),
	"online": ("players online", "jugadores conectados"),
	"max_players": ("max players", "máximo de jugadores"),
	"server_name": ("server name", "nombre del server"),
	"tps": ("server TPS", "TPS del server"),
	"mspt": ("ms per tick", "ms por tick"),
	"ram": ("server RAM", "RAM del server"),
	"ram_pct": ("server RAM %", "RAM del server %"),
	"ram_used": ("used RAM (MB)", "RAM usada (MB)"),
	"ram_max": ("max RAM (MB)", "RAM máxima (MB)"),
	"cpu": ("server CPU %", "CPU del server %"),
	"uptime": ("uptime", "tiempo encendido"),
	"fps": ("your FPS ★", "tus FPS ★"),
	"client_ram": ("your RAM ★", "tu RAM ★"),
	"client_ram_pct": ("your RAM % ★", "tu RAM % ★"),
	"my_ping": ("your ping", "tu ping"),
	"local_time": ("your clock", "tu hora"),
	"local_time_s": ("your clock + seconds", "tu hora + segundos"),
	"local_date": ("your date", "tu fecha"),
	"date": ("server date", "fecha del server"),
	"time": ("server time", "hora del server"),
	"world": ("world", "mundo"),
	"dimension": ("dimension id", "id de dimensión"),
	"biome": ("biome", "bioma"),
	"x": ("X", "X"),
	"y": ("Y", "Y"),
	"z": ("Z", "Z"),
	"health": ("health", "vida"),
	"max_health": ("max health", "vida máxima"),
	"food": ("food", "comida"),
	"level": ("XP level", "nivel de XP"),
	"gamemode": ("game mode", "modo de juego"),
	"deaths": ("deaths", "muertes"),
	"kills": ("player kills", "asesinatos"),
	"mob_kills": ("mob kills", "mobs matados"),
	"playtime": ("play time", "tiempo jugado"),
	"afk": ("AFK (true/false)", "AFK (true/false)"),
	"op": ("is OP", "es OP"),
	"team": ("team", "equipo"),
	"is_day": ("is it day (true/false)", "es de día (true/false)"),
	"moon_phase": ("moon phase (1-8)", "fase de la luna (1-8)"),
	"staff_online": ("OPs online", "OPs conectados"),
	"afk_online": ("AFK players", "jugadores AFK"),
	"difficulty": ("difficulty", "dificultad"),
	"view_distance": ("view distance", "distancia de visión"),
	"sim_distance": ("simulation distance", "distancia de simulación"),
	"entities": ("loaded entities", "entidades cargadas"),
	"chunks": ("loaded chunks", "chunks cargados"),
	"worlds": ("worlds", "mundos"),
	"threads": ("server threads", "hilos del server"),
	"java_version": ("Java version", "versión de Java"),
	"server_mods": ("server mods", "mods del server"),
	"port": ("server port", "puerto del server"),
	"display_name": ("display name", "nombre visible"),
	"xp": ("total XP points", "puntos de XP totales"),
	"xp_pct": ("XP bar %", "barra de XP %"),
	"armor": ("armor points", "puntos de armadura"),
	"saturation": ("saturation", "saturación"),
	"air": ("air %", "aire %"),
	"light": ("light level", "nivel de luz"),
	"facing": ("facing (N/S/E/W)", "dirección (N/S/E/W)"),
	"chunk_x": ("chunk X", "chunk X"),
	"chunk_z": ("chunk Z", "chunk Z"),
	"held_item": ("item in hand", "ítem en la mano"),
	"language": ("game language", "idioma del juego"),
	"jumps": ("jumps", "saltos"),
	"fish": ("fish caught", "peces pescados"),
	"walked": ("distance walked", "distancia caminada"),
	"since_death": ("time since last death", "tiempo desde la última muerte"),
	"local_weekday": ("your weekday ★", "tu día de la semana ★"),
	"render_distance": ("your render distance ★", "tu distancia de render ★"),
	"resolution": ("your resolution ★", "tu resolución ★"),
	"gpu": ("your graphics card ★", "tu tarjeta gráfica ★"),
	"client_mods": ("your mods ★", "tus mods ★"),
	"rank": ("Chaos Ranks badge", "badge de Chaos Ranks"),
	"rank_name": ("rank name", "nombre del rango"),
	"has_rank": ("has a rank", "tiene rango"),
	"day": ("world day", "día del mundo"),
	"world_time": ("world clock", "hora del mundo"),
	"weather": ("weather", "clima"),
	"weather_icon": ("weather symbol", "símbolo del clima"),
	"motd": ("MOTD", "MOTD"),
	"version": ("MC version", "versión de MC"),
}

COLORS = {
	"dark_red": ("Dark red", "Rojo oscuro"), "red": ("Red", "Rojo"), "light_red": ("Light red", "Rojo claro"),
	"coral": ("Coral", "Coral"), "salmon": ("Salmon", "Salmón"), "orange": ("Orange", "Naranja"),
	"light_orange": ("Light orange", "Naranja claro"), "copper": ("Copper", "Cobre"),
	"gold": ("Gold", "Oro"), "amber": ("Amber", "Ámbar"), "yellow": ("Yellow", "Amarillo"),
	"light_yellow": ("Light yellow", "Amarillo claro"), "cream": ("Cream", "Crema"), "mustard": ("Mustard", "Mostaza"),
	"lime": ("Lime", "Lima"), "neon_green": ("Neon green", "Verde neón"), "mint": ("Mint", "Menta"),
	"emerald": ("Emerald", "Esmeralda"), "green": ("Green", "Verde"), "dark_green": ("Dark green", "Verde oscuro"),
	"olive": ("Olive", "Oliva"), "turquoise": ("Turquoise", "Turquesa"),
	"diamond": ("Diamond", "Diamante"), "cyan": ("Cyan", "Cian"), "sky": ("Sky", "Cielo"),
	"light_blue": ("Light blue", "Celeste"), "blue": ("Blue", "Azul"), "lapis": ("Lapis", "Lapislázuli"),
	"navy": ("Navy", "Azul marino"), "ice": ("Ice", "Hielo"),
	"purple": ("Purple", "Morado"), "amethyst": ("Amethyst", "Amatista"), "lavender": ("Lavender", "Lavanda"),
	"violet": ("Violet", "Violeta"), "magenta": ("Magenta", "Magenta"), "pink": ("Pink", "Rosa"),
	"light_pink": ("Light pink", "Rosa claro"), "hot_pink": ("Hot pink", "Rosa fuerte"),
	"brown": ("Brown", "Marrón"), "dark_brown": ("Dark brown", "Marrón oscuro"), "sand": ("Sand", "Arena"),
	"tan": ("Tan", "Canela"), "rust": ("Rust", "Óxido"), "wine": ("Wine", "Vino"),
	"white": ("White", "Blanco"), "light_gray": ("Light gray", "Gris claro"), "silver": ("Silver", "Plata"),
	"gray": ("Gray", "Gris"), "dark_gray": ("Dark gray", "Gris oscuro"), "charcoal": ("Charcoal", "Carbón"),
	"black": ("Black", "Negro"), "obsidian": ("Obsidian", "Obsidiana"),
	"youtube": ("YouTube", "YouTube"), "twitch": ("Twitch", "Twitch"), "discord": ("Discord", "Discord"),
	"kick": ("Kick", "Kick"), "spotify": ("Spotify", "Spotify"), "tiktok": ("TikTok", "TikTok"),
	"instagram": ("Instagram", "Instagram"), "twitter": ("Twitter / X", "Twitter / X"),
}


def main():
	en, es = {}, {}
	for table, prefix, suffix in ((T, "", ""), (SNIPPETS, "snippet.", ""), (DESCS, "snippet.", ".desc"),
			(PLACEHOLDERS, "ph.", ""), (COLORS, "color.", "")):
		for k, (e, s) in table.items():
			en["chaostablist." + prefix + k + suffix] = e
			es["chaostablist." + prefix + k + suffix] = s
	LANG.mkdir(parents=True, exist_ok=True)
	(LANG / "en_us.json").write_text(json.dumps(en, indent="\t", ensure_ascii=False) + "\n", encoding="utf-8")
	for name in SPANISH:
		(LANG / f"{name}.json").write_text(json.dumps(es, indent="\t", ensure_ascii=False) + "\n", encoding="utf-8")
	print(len(en), "claves")


if __name__ == "__main__":
	main()
